### ISSUE TITLE
On capture of image from camera getting more than 1 photo

### ISSUE THREAD

**Issue by inceptiveDipak** [DroidNinja/Android-FilePicker#3]
Hello @DroidNinja 
After downloading give apk and installed it on my moto e device. On start of app and taking photo from camera it will capture photo more than 1 photo, Please check out this issue.
Thank you

**Comment by DroidNinja** [comment]
Thanks for filing this issue. I think there's mistake in camera intent. I will check out this ASAP.

**Comment by DroidNinja** [comment]
Hey @inceptiveDipak I have fixed the issue. Just checkout the latest build and please confirm.

**Comment by inceptiveDipak** [comment]
Hey @DroidNinja Thank for reply. Let me check out it.

**Comment by inceptiveDipak** [comment]
Hey @DroidNinja The problem is not solved it will get same result as previous just downloaded apk. I will tested it on my android marshmallow 6.0.1. Can you please check again. Thank you. !!

**Comment by DroidNinja** [comment]
It was mediascanner issue. Just checked on 5.0.1. Please check latest build and confirm

**Comment by inceptiveDipak** [comment]
Hey @DroidNinja  Thanks for help.

**Comment by inceptiveDipak** [comment]
@DroidNinja issue solved

**Comment by ahmedMubarak2024** [comment]
hi @DroidNinja  i am working with version 2.2.0 and on android 6.0 api 23 and there is two images generated on in the camera folder and anther in the pictures folder
